from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from products.models import Product, Allergen
from marketplace.models import Category
import random
from decimal import Decimal

User = get_user_model()

# This command creates 5 demo products linked to the current Superuser (Admin). 
# Seperate to create_demo_data.py which creates a wider variety of data for testing.
class Command(BaseCommand):
    help = 'Generates products linked to the current Superuser (Admin)'

    def handle(self, *args, **kwargs):
        # 1. Get the Admin User (Fail safely if you haven't created one yet)
        try:
            admin_user = User.objects.filter(is_superuser=True).first()
            if not admin_user:
                self.stdout.write(self.style.ERROR("No Superuser found! Create one first."))
                return
        except Exception as e:
            self.stdout.write(self.style.ERROR(f"Error finding user: {e}"))
            return

        self.stdout.write(f"Linking products to admin: {admin_user.username}")

        demo_category, _ = Category.objects.get_or_create(
            name="General Produce",
            defaults={'description': 'A category for demo products.'}
        )

        # 2. Create Basic Allergens (TC-015)
        allergens_list = ['Peanuts', 'Gluten', 'Dairy', 'Shellfish']
        created_allergens = []
        for name in allergens_list:
            obj, _ = Allergen.objects.get_or_create(name=name)
            created_allergens.append(obj)

        # 3. Create 5 Test Products
        product_names = ['Test Burger', 'Test Apple', 'Test Yogurt', 'Test Bread', 'Test Soup']
        
        for name in product_names:
            # Delete if exists so we don't duplicate every time we run it
            Product.objects.filter(name=name).delete()
            
            product = Product.objects.create(
                producer=admin_user,  # Linking to Admin
                name=name,
                description="This is a test product generated by command A.",
                price=Decimal(random.uniform(5.00, 20.00)),
                unit="item",
                stock_quantity=100,
                category=demo_category,
                is_available=True
            )
            
            # Randomly add an allergen
            if random.choice([True, False]):
                product.allergens.add(random.choice(created_allergens))
                
            self.stdout.write(f"Created: {product.name}")

        self.stdout.write(self.style.SUCCESS('Successfully seeded 5 test products for Admin.'))