# Generated by Django 6.0.1 on 2026-02-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used to filter in the URL (Automatically filled)', unique=True),
        ),
    ]
