# Generated by Django 6.0.1 on 2026-04-14 20:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_educationalpost_likes'),
        ('products', '0011_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecipe',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Brief intro to the recipe.')),
                ('ingredients', models.TextField(help_text='List ingredients, one per line.')),
                ('instructions', models.TextField(help_text='Step-by-step cooking instructions.')),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('seasonal_tag', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn/Winter'), ('year_round', 'Year Round')], default='year_round', max_length=20)),
                ('is_published', models.BooleanField(default=False, help_text='Only published recipes are visible to customers.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producer', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'PRODUCER'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Recipe',
                'verbose_name_plural': 'historical Recipes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Brief intro to the recipe.')),
                ('ingredients', models.TextField(help_text='List ingredients, one per line.')),
                ('instructions', models.TextField(help_text='Step-by-step cooking instructions.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('seasonal_tag', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn/Winter'), ('year_round', 'Year Round')], default='year_round', max_length=20)),
                ('is_published', models.BooleanField(default=False, help_text='Only published recipes are visible to customers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_products', models.ManyToManyField(blank=True, help_text='Products featured in this recipe. Will appear on their product pages.', related_name='recipes', to='products.product')),
                ('producer', models.ForeignKey(limit_choices_to={'role': 'PRODUCER'}, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
        ),
    ]
