# Generated by Django 6.0.1 on 2026-04-15 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_historicalrecipe_recipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='saved_by',
            field=models.ManyToManyField(blank=True, help_text='Customers who have saved this recipe.', related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
