# Generated by Django 6.0.1 on 2026-04-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_recipe_saved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalpost',
            name='post_type',
            field=models.CharField(choices=[('RECIPE', 'Recipe'), ('FARM_STORY', 'Farm Story'), ('SEASONAL_UPDATE', 'Seasonal Update'), ('STORAGE_GUIDE', 'Storage Guide')], default='SEASONAL_UPDATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaleducationalpost',
            name='post_type',
            field=models.CharField(choices=[('RECIPE', 'Recipe'), ('FARM_STORY', 'Farm Story'), ('SEASONAL_UPDATE', 'Seasonal Update'), ('STORAGE_GUIDE', 'Storage Guide')], default='SEASONAL_UPDATE', max_length=20),
        ),
    ]
