# Generated by Django 6.0.1 on 2026-04-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_educationalpost_post_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalpost',
            name='post_type',
            field=models.CharField(choices=[('FARM_STORY', 'Farm Story'), ('SEASONAL_UPDATE', 'Seasonal Update'), ('STORAGE_GUIDE', 'Storage Guide')], default='SEASONAL_UPDATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaleducationalpost',
            name='post_type',
            field=models.CharField(choices=[('FARM_STORY', 'Farm Story'), ('SEASONAL_UPDATE', 'Seasonal Update'), ('STORAGE_GUIDE', 'Storage Guide')], default='SEASONAL_UPDATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='ingredients',
            field=models.TextField(help_text='List ingredients, one for each line.'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='seasonal_tag',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('year_round', 'Year Round')], default='year_round', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='List ingredients, one for each line.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='seasonal_tag',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('year_round', 'Year Round')], default='year_round', max_length=20),
        ),
    ]
