# Generated by Django 6.0.1 on 2026-05-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_educationalpost_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='historicaleducationalpost',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
