# Generated by Django 6.0.1 on 2026-05-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_comment'),
        ('products', '0019_merge_20260505_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='featured_products',
            field=models.ManyToManyField(blank=True, help_text='Products from other producers featured in this recipe.', related_name='featured_in_recipes', to='products.product'),
        ),
    ]
