# Generated by Django 6.0.1 on 2026-05-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_recipe_featured_products'),
        ('marketplace', '0014_historicalcomment'),
    ]

    operations = [
    ]
