# Generated by Django 6.0.1 on 2026-02-25 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('PRODUCER', 'Producer'), ('COMMUNITY_GROUP', 'Community Group'), ('RESTAURANT', 'Restaurant'), ('ADMIN', 'Administrator')], default='CUSTOMER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMMUNITY_GROUP', 'Community Group'), ('RESTAURANT', 'Restaurant / Café')], default='INDIVIDUAL', max_length=20)),
                ('organisation_name', models.CharField(blank=True, help_text='Required for community groups and restaurants.', max_length=200)),
                ('delivery_address', models.TextField()),
                ('postcode', models.CharField(help_text='Used for food-miles calculation.', max_length=10)),
                ('receive_surplus_alerts', models.BooleanField(default=True, help_text='Opt-in for last-minute surplus deal notifications.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=10)),
                ('lead_time_hours', models.PositiveIntegerField(default=48, help_text='Minimum hours notice required before a delivery.')),
                ('organic_certified', models.BooleanField(default=False)),
                ('certification_body', models.CharField(blank=True, help_text='E.g. Soil Association certificate reference.', max_length=100)),
                ('bank_sort_code', models.CharField(blank=True, max_length=8)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('tax_reference', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'PRODUCER'}, on_delete=django.db.models.deletion.CASCADE, related_name='producer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producer Profile',
                'verbose_name_plural': 'Producer Profiles',
            },
        ),
    ]
