# Generated by Django 6.0.1 on 2026-03-04 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerprofile',
            name='lead_time_hours',
            field=models.PositiveIntegerField(default=48, help_text='Minimum hours notice required before a delivery.', validators=[django.core.validators.MinValueValidator(48)]),
        ),
    ]
