# Generated by Django 6.0.1 on 2026-03-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicalcustomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='receive_educational_emails',
            field=models.BooleanField(default=True, help_text='Receive recipes, farm stories and seasonal updates via email.'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='subscribed_producers',
            field=models.ManyToManyField(blank=True, help_text='Producers this customer is subscribed to.', related_name='subscribers', to='accounts.producerprofile'),
        ),
    ]
