# Generated by Django 6.0.1 on 2026-04-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminprofile'),
        ('accounts', '0004_customerprofile_receive_educational_emails_and_more'),
    ]

    operations = [
    ]
