# Generated by Django 6.0.1 on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customerprofile_receive_educational_emails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("PRODUCER", "Producer"),
                    ("COMMUNITY_GROUP", "Community Group"),
                    ("RESTAURANT", "Restaurant"),
                    ("AI_ENGINEER", "AI Engineer"),
                    ("ADMIN", "Administrator"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("PRODUCER", "Producer"),
                    ("COMMUNITY_GROUP", "Community Group"),
                    ("RESTAURANT", "Restaurant"),
                    ("AI_ENGINEER", "AI Engineer"),
                    ("ADMIN", "Administrator"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
    ]
