# Generated by Django 6.0.1 on 2026-04-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerprofile_receive_educational_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell the community about your farm/business and your ethical practices.'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='notify_general',
            field=models.BooleanField(default=True, help_text='Receive general updates, seasonal digests and platform news.'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='vacation_mode',
            field=models.BooleanField(default=False, help_text='Pause your store. Go on vacation. Customers will not be able to place new orders.'),
        ),
    ]
