# Generated by Django 6.0.1 on 2026-04-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20260414_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='low_stock_email_notifications',
            field=models.BooleanField(default=True, help_text="Receive an email when a product's stock falls below its threshold."),
        ),
    ]
