# Generated by Django 6.0.1 on 2026-04-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_producerprofile_bio_producerprofile_notify_general_and_more'),
        ('accounts', '0006_producerprofile_low_stock_email_notifications'),
    ]

    operations = [
    ]
