# Generated by Django 6.0.1 on 2026-05-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260430_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='The Stripe Connected Account ID (e.g. acct_12345).', max_length=100),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False, help_text='Indicates whether the producer has fully completed the Stripe onboarding flow.'),
        ),
    ]
