# Generated by Django 6.0.1 on 2026-05-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260430_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='charity_education_status',
            field=models.CharField(blank=True, help_text='Provide your registered charity number, school URN, or education status.', max_length=200, verbose_name='Charity / Education Status'),
        ),
    ]
