# Generated by Django 6.0.1 on 2026-05-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_stripe_connect_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producerprofile',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='bank_sort_code',
        ),
    ]
