# Generated by Django 6.0.1 on 2026-04-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_name", models.CharField(max_length=120)),
                ("model_version", models.CharField(max_length=64)),
                ("framework", models.CharField(blank=True, max_length=64)),
                ("manifest_json", models.JSONField(blank=True, default=dict)),
                ("checksum", models.CharField(max_length=128)),
                ("artifact_path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_ai_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("anonymised", models.BooleanField(default=True)),
                ("filter_json", models.JSONField(blank=True, default=dict)),
                ("output_path", models.CharField(blank=True, max_length=255)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retraining_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="InferenceRequestLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_path", models.CharField(max_length=255)),
                ("color_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("size_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ripeness_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=5)),
                ("predicted_class", models.CharField(max_length=100)),
                (
                    "ai_reported_grade",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "authoritative_grade",
                    models.CharField(choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1),
                ),
                ("recommendation_action", models.CharField(max_length=120)),
                ("explanation_payload", models.JSONField(blank=True, default=dict)),
                ("model_version_used", models.CharField(max_length=64)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("grading_policy_version", models.CharField(max_length=32)),
                ("ai_grade_mismatch", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inference_requests",
                        to="products.product",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ActiveModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_activations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activations",
                        to="ai_engineering.aimodelversion",
                    ),
                ),
            ],
            options={"ordering": ["-activated_at"]},
        ),
        migrations.CreateModel(
            name="ProducerOverrideEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("accepted_recommendation", models.BooleanField()),
                (
                    "override_grade",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("override_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inference_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="ai_engineering.inferencerequestlog",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="aimodelversion",
            constraint=models.UniqueConstraint(
                fields=("model_name", "model_version"), name="unique_model_name_version"
            ),
        ),
    ]
