# Generated by Django 6.0.1 on 2026-04-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engineering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferencerequestlog',
            name='latency_ms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
