# Generated by Django 6.0.1 on 2026-04-19 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engineering', '0002_alter_inferencerequestlog_latency_ms'),
        ('products', '0011_productbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencerequestlog',
            name='aggregation_method',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='inferencerequestlog',
            name='committed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inferencerequestlog',
            name='image_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inferencerequestlog',
            name='lot_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inferencerequestlog',
            name='scan_mode',
            field=models.CharField(choices=[('preview', 'Preview'), ('batch_intake', 'Batch Intake')], default='preview', max_length=20),
        ),
        migrations.CreateModel(
            name='BatchGradeChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('new_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_changes', to='products.productbatch')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_grade_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceInputImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('ordinal', models.PositiveIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('inference_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_images', to='ai_engineering.inferencerequestlog')),
            ],
            options={
                'ordering': ['inference_log_id', 'ordinal'],
                'constraints': [models.UniqueConstraint(fields=('inference_log', 'ordinal'), name='unique_inference_input_ordinal')],
            },
        ),
        migrations.CreateModel(
            name='IntakeCommitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_commits', to='products.productbatch')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_commit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('producer', 'idempotency_key'), name='unique_producer_idempotency_key')],
            },
        ),
    ]
