# Generated by Django 6.0.1 on 2026-04-24 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engineering', '0003_inferencerequestlog_aggregation_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_items', models.JSONField(default=list)),
                ('recommended_items', models.JSONField(default=list)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('model_version_used', models.CharField(max_length=64)),
                ('explanation_payload', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
