# Generated by Django 6.0.1 on 2026-04-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engineering', '0004_recommendationrequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='export_type',
            field=models.CharField(choices=[('QUALITY', 'Quality Retraining (Task 2)'), ('ORDER_FBT', 'Order History for FBT (Task 1)')], default='QUALITY', max_length=20),
        ),
    ]
