# Generated by Django 6.0.1 on 2026-04-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engineering', '0005_exportjob_export_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='export_type',
            field=models.CharField(choices=[('QUALITY', 'Quality Retraining (Task 2)'), ('ORDER_FBT', 'Order History for FBT (Task 1)'), ('NEXT_BASKET', 'User Features for Next Basket (Task 1)')], default='QUALITY', max_length=20),
        ),
    ]
