# Generated by Django 6.0.1 on 2026-04-25 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engineering', '0006_alter_exportjob_export_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminExplanationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_prediction', models.CharField(max_length=100)),
                ('generated_explanation', models.JSONField(blank=True, default=dict)),
                ('agreed_with_model', models.BooleanField()),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inference_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_audit_reviews', to='ai_engineering.inferencerequestlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
