# Generated by Django 6.0.1 on 2026-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engineering", "0007_adminexplanationreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="produceroverrideevent",
            name="color_accepted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="produceroverrideevent",
            name="size_accepted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="produceroverrideevent",
            name="ripeness_accepted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="produceroverrideevent",
            name="override_color_score",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="produceroverrideevent",
            name="override_size_score",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="produceroverrideevent",
            name="override_ripeness_score",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
