# Generated by Django 6.0.1 on 2026-04-19 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0011_productbatch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='If set, AI-discounted price is used. Falls back to live product price.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='products.productbatch'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'batch'), name='unique_cart_product_batch'),
        ),
    ]
