# Generated by Django 6.0.1 on 2026-03-04 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_deleted_at_order_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Legacy field — per-producer dates are on ProducerOrder.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_producer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='producer_payment',
            field=models.DecimalField(decimal_places=2, help_text='Total owed to all producers (subtotal − commission).', max_digits=10),
        ),
        migrations.CreateModel(
            name='ProducerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('delivery_date', models.DateField(help_text="Requested delivery date for this producer's items.")),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Network commission rate snapshot (e.g. 0.05 = 5%).', max_digits=4)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producer_payment', models.DecimalField(decimal_places=2, default=0, help_text='Amount owed to this producer (subtotal − commission).', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.order')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_sub_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['delivery_date'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='producer_order',
            field=models.ForeignKey(blank=True, help_text='The producer sub-order this item belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.producerorder'),
        ),
    ]
