# Generated by Django 6.0.1 on 2026-03-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_multi_producer_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='producer',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='producer_order',
            field=models.ForeignKey(help_text='The producer sub-order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.producerorder'),
        ),
    ]
