# Generated by Django 6.0.1 on 2026-03-05 00:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_defaults_to_order_financials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='producer_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total owed to all producers (subtotal − commission).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
