# Generated by Django 6.0.1 on 2026-03-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special delivery instructions or notes for the producer.', null=True),
        ),
    ]
