# Generated by Django 6.0.1 on 2026-03-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_special_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='producerorder',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special delivery instructions or notes for this producer.', null=True),
        ),
    ]
