# Generated by Django 6.0.1 on 2026-03-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_special_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_ORDER', 'New Order'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('LOW_STOCK', 'Low Stock Alert')], max_length=20),
        ),
    ]
