# Generated by Django 6.0.1 on 2026-03-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_historicalorder_historicalproducerorder'),
        ('orders', '0008_remove_order_special_instructions_and_more'),
    ]

    operations = [
    ]
