# Generated by Django 6.0.1 on 2026-03-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_merge_20260316_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='historicalproducerorder',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special delivery instructions or notes for this producer.', null=True),
        ),
    ]
