# Generated by Django 6.0.1 on 2026-03-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_notification_product'),
        ('orders', '0010_remove_historicalorder_special_instructions_and_more'),
    ]

    operations = [
    ]
