# Generated by Django 6.0.1 on 2026-03-25 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_educationalpost_historicaleducationalpost'),
        ('orders', '0011_merge_20260317_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='educational_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='marketplace.educationalpost'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_ORDER', 'New Order'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('LOW_STOCK', 'Low Stock Alert'), ('NEW_POST', 'New Community Post')], max_length=20),
        ),
    ]
