# Generated by Django 6.0.1 on 2026-04-19 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_historicalorder_status_and_more'),
        ('products', '0011_productbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The graded lot this item was purchased from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productbatch'),
        ),
    ]
