# Generated by Django 6.0.1 on 2026-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_historicalorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (Review Needed)'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DISPATCHED', 'Ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (Review Needed)'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DISPATCHED', 'Ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12),
        ),
    ]
