# Generated by Django 6.0.1 on 2026-05-04 12:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_historicalorder_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday 00:00:00 of the settlement window.')),
                ('week_end', models.DateField(help_text='Sunday (end of day) of the settlement window.')),
                ('gross_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(limit_choices_to={'role': 'PRODUCER'}, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end', 'producer')},
            },
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_ref', models.CharField(blank=True, help_text='Stripe Transfer ID or deterministic mock reference (e.g. MOCK-{settlement_id}-{producer_id}).', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer_order', models.OneToOneField(help_text='Each ProducerOrder can only appear in one settlement.', on_delete=django.db.models.deletion.CASCADE, related_name='settlement_line', to='orders.producerorder')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.settlement')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
