# Generated by Django 6.0.1 on 2026-04-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_historicalorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorderitem',
            name='unit_price_at_setup',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the product when the template was created.', max_digits=10, null=True),
        ),
    ]
