# Generated by Django 6.0.1 on 2026-04-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_historicalorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='surplus_discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage applied if this was a surplus deal (0 if not).'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='was_surplus_deal',
            field=models.BooleanField(default=False, help_text='Whether this item was purchased as part of a surplus deal.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_ORDER', 'New Order'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_STATUS_UPDATE', 'Order Status Update'), ('ORDER_CANCELLED', 'Order Cancelled'), ('LOW_STOCK', 'Low Stock Alert'), ('NEW_POST', 'New Community Post'), ('SEASONAL_DIGEST', 'Seasonal Planning Reminder'), ('RECURRING_DRAFT', 'Recurring Order Ready'), ('RECURRING_ISSUE', 'Recurring Order Issue'), ('SURPLUS_DEAL', 'Surplus Deal')], max_length=20),
        ),
    ]
