# Generated by Django 6.0.1 on 2026-04-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_recurringorderitem_unit_price_at_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorderitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringorderitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
