# Generated by Django 6.0.1 on 2026-05-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_surplus_discount_percentage_and_more'),
        ('orders', '0017_recurringorderitem_deleted_at_and_more'),
    ]

    operations = [
    ]
