name: Continuous Integration

on:
  push: # Run workflow when pushed or PR to main
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Adds a manual 'Run' button in Github Actions.

jobs: # Each job runs on a VM.
  test-and-lint:
    runs-on: ubuntu-latest

    env: # Environment variables defined.
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost 127.0.0.1 [::1] 0.0.0.0"
      POSTGRES_DB: bristol_food_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    services: # (Runs docker)
      # Define DB to ensure its available to the runner 
      db:
        image: postgres:15
        env: # Sets environment variables inside Postgres container
          POSTGRES_DB: bristol_food_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
        ports:
          - 5432:5432
        # Wait until postgres is confirmed healthy before testing
        options: >- 
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 # Downloads repository into runner

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caches pip dependencies to make ci fast.
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff coverage bandit safety 
      
      - name: Check Code Formatting & Linting
        run: | # Checks formatting is properly formatted & looks for unused imports, undefined variables, etc...
          ruff format --check . 
          ruff check .
      
      - name: Security Scan (On pip dependencies)
        run: safety check # Runs a check on a database of known vulnerable/hacked python packages

      - name: Security Scan (On code)
      # Scans python code for hardcoded passwords, sql injections, etc... (-ll -ii only reports medium and high severity issues, exclude venv and tests bcuz tests can have dummy passwords)
        run: bandit -r . -ll -ii -x ./venv,./tests,*/management/commands/*

      - name: Django Integrity - Check Missing Migrations
        # Fails if forgotten to run 'makemigrations'
        run: python manage.py makemigrations --check --dry-run

      - name: Django Integrity - System Checks
        # Validates settings.py and general Django configuration
        run: python manage.py check

      - name: Django Integrity - Test Static Files
        # Ensures collectstatic works for production deployment
        run: python manage.py collectstatic --noinput

      - name: Run Migrations
        run: python manage.py migrate

      - name: Run Tests & Check Coverage
        run: |
          coverage run manage.py test
          coverage report
          coverage html
      
      - name: Upload Coverage HTML Report # To github actions
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/ # Default
          retention-days: 14 # Auto-deletes after 2 weeks to save GitHub storage space

  # Acts as Continuous Deployment check (docker only as we dont have any prod server setup yet)
  build-docker-image:
    needs: test-and-lint
    runs-on: ubuntu-latest
    if github.ref == 'refs/heads/main' # Only on main.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image 
        # This tests that Dockerfile successfully builds an image.
        run: docker build -t bristol-food-network:latest .

    