# Generated by Django 6.0.1 on 2026-03-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_deleted_at_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, help_text='When was this harvested or prepared?', null=True),
        ),
    ]
