# Generated by Django 6.0.1 on 2026-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_harvest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_year_round',
            field=models.BooleanField(default=False, help_text='If checked, seasonal start and end dates will be ignored.', verbose_name='Available all year round?'),
        ),
    ]
