# Generated by Django 6.0.1 on 2026-03-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_harvest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_notified',
            field=models.BooleanField(default=False, help_text='Internal flag to prevent spamming emails.'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert me when stock drops to or below this number.'),
        ),
    ]
