# Generated by Django 6.0.1 on 2026-03-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_historicalproduct'),
        ('products', '0005_product_is_year_round'),
    ]

    operations = [
    ]
