# Generated by Django 6.0.1 on 2026-03-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20260316_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='is_year_round',
            field=models.BooleanField(default=False, help_text='If checked, seasonal start and end dates will be ignored.', verbose_name='Available all year round?'),
        ),
    ]
