# Generated by Django 6.0.1 on 2026-03-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_low_stock_notified_and_more'),
        ('products', '0007_historicalproduct_is_year_round'),
    ]

    operations = [
    ]
