# Generated by Django 6.0.1 on 2026-03-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20260317_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='low_stock_notified',
            field=models.BooleanField(default=False, help_text='Internal flag to prevent spamming emails.'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert me when stock drops to or below this number.'),
        ),
    ]
