# Generated by Django 6.0.1 on 2026-03-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_historicalproduct_low_stock_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='season_end',
            field=models.CharField(blank=True, help_text='MM-DD (e.g., 08-31)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='season_start',
            field=models.CharField(blank=True, help_text='MM-DD (e.g., 06-01)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='season_end',
            field=models.CharField(blank=True, help_text='MM-DD (e.g., 08-31)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='season_start',
            field=models.CharField(blank=True, help_text='MM-DD (e.g., 06-01)', max_length=5, null=True),
        ),
    ]
