# Generated by Django 6.0.1 on 2026-04-19 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engineering', '0002_alter_inferencerequestlog_latency_ms'),
        ('products', '0010_alter_historicalproduct_season_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Grade A (Premium)'), ('B', 'Grade B (Standard)'), ('C', 'Grade C (Clearance)')], max_length=1)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Price before any AI discount.', max_digits=6)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='AI-recommended discount (0-100).', max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Computed: base_price * (1 - discount/100).', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inference_log', models.ForeignKey(blank=True, help_text='The AI scan that created this lot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='ai_engineering.inferencerequestlog')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Batches',
                'constraints': [models.UniqueConstraint(fields=('inference_log', 'product'), name='unique_batch_per_inference')],
            },
        ),
    ]
