# Generated by Django 6.0.1 on 2026-05-03 18:01

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_review'),
    ]

    operations = [
        TrigramExtension(),
    ]
