# Generated by Django 6.0.1 on 2026-04-30 22:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurplusDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveIntegerField(help_text='Discount percentage (10–50%).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)])),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Snapshot of the product price when the deal was created.', max_digits=6)),
                ('discounted_price', models.DecimalField(decimal_places=2, help_text='Calculated discounted price.', max_digits=6)),
                ('note', models.TextField(blank=True, help_text="e.g. 'Perfect condition, must sell quickly to avoid waste'")),
                ('expires_at', models.DateTimeField(help_text='When this surplus deal automatically expires.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Producer can deactivate if stock sells out.')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_deal', to='products.product')),
            ],
            options={
                'verbose_name': 'Surplus Deal',
                'verbose_name_plural': 'Surplus Deals',
            },
        ),
    ]
