# Generated by Django 6.0.1 on 2026-04-19 16:33

from django.db import migrations, models


def backfill_unbatched_stock(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductBatch = apps.get_model("products", "ProductBatch")

    active_totals = {}
    for row in (
        ProductBatch.objects.filter(is_active=True)
        .values("product_id")
        .annotate(total=models.Sum("stock_quantity"))
    ):
        active_totals[row["product_id"]] = int(row["total"] or 0)

    for product in Product.objects.all().only("id", "stock_quantity"):
        active_batch_stock = active_totals.get(product.id, 0)
        unbatched = max(int(product.stock_quantity or 0) - active_batch_stock, 0)
        Product.objects.filter(pk=product.pk).update(unbatched_stock_quantity=unbatched)


def reverse_backfill_unbatched_stock(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.all().update(unbatched_stock_quantity=0)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='unbatched_stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Internal: stock not yet allocated to graded batches.'),
        ),
        migrations.AddField(
            model_name='product',
            name='unbatched_stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Internal: stock not yet allocated to graded batches.'),
        ),
        migrations.RunPython(backfill_unbatched_stock, reverse_backfill_unbatched_stock),
    ]
