# Generated by Django 6.0.1 on 2026-04-28 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_is_visible_to_moderation_status(apps, schema_editor):
    Review = apps.get_model('products', 'Review')
    
    # Map is_visible=True -> APPROVED, is_visible=False -> REJECTED
    Review.objects.filter(is_visible=True).update(moderation_status='APPROVED')
    Review.objects.filter(is_visible=False).update(moderation_status='REJECTED')
    
    # Existing producer responses should also get an initial APPROVED state so they don't
    # all show up in the new Action Required queue initially.
    Review.objects.exclude(producer_response='').update(response_moderation_status='APPROVED')

def reverse_migrate_is_visible(apps, schema_editor):
    Review = apps.get_model('products', 'Review')
    
    Review.objects.filter(moderation_status='REJECTED').update(is_visible=False)
    Review.objects.exclude(moderation_status='REJECTED').update(is_visible=True)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_historicalorder_status_and_more'),
        ('products', '0011_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='products_re_product_8ba9fc_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected/Hidden')], default='PENDING', help_text='Pending and Approved reviews are publicly visible. Rejected reviews are hidden.', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='response_moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='response_moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='response_moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected/Hidden')], default='PENDING', help_text="Status of the producer's reply. Reset to Pending on every edit.", max_length=20),
        ),
        migrations.RunPython(
            migrate_is_visible_to_moderation_status,
            reverse_code=reverse_migrate_is_visible
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'moderation_status'], name='products_re_product_a212bd_idx'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_visible',
        ),
    ]
