# Generated by Django 6.0.1 on 2026-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_surplusdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusdeal',
            name='surplus_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of items available at the surplus discount.'),
        ),
    ]
