# Generated by GitHub Copilot on 2026-04-19

from decimal import Decimal

from django.db import migrations, models


def _canonical_discount_for_grade(grade):
    return {
        "A": Decimal("0"),
        "B": Decimal("10"),
        "C": Decimal("25"),
    }.get((grade or "").upper(), Decimal("0"))


def consolidate_active_grade_buckets(apps, schema_editor):
    ProductBatch = apps.get_model("products", "ProductBatch")
    db_alias = schema_editor.connection.alias

    duplicate_groups = (
        ProductBatch.objects.using(db_alias)
        .filter(is_active=True)
        .values("product_id", "grade")
        .annotate(batch_count=models.Count("id"))
        .filter(batch_count__gt=1)
    )

    for group in duplicate_groups:
        rows = list(
            ProductBatch.objects.using(db_alias)
            .filter(
                product_id=group["product_id"],
                grade=group["grade"],
                is_active=True,
            )
            .order_by("created_at", "id")
        )

        if len(rows) < 2:
            continue

        survivor = rows[0]
        total_stock = sum(int(row.stock_quantity or 0) for row in rows)
        canonical_discount = _canonical_discount_for_grade(group["grade"])
        base_price = Decimal(str(survivor.base_price or 0))
        final_price = (base_price * (Decimal("1") - canonical_discount / Decimal("100"))).quantize(
            Decimal("0.01")
        )

        ProductBatch.objects.using(db_alias).filter(pk=survivor.pk).update(
            stock_quantity=total_stock,
            discount_percent=canonical_discount,
            final_price=final_price,
            is_active=total_stock > 0,
        )

        duplicate_ids = [row.id for row in rows[1:]]
        if duplicate_ids:
            ProductBatch.objects.using(db_alias).filter(pk__in=duplicate_ids).update(
                stock_quantity=0,
                is_active=False,
            )


def reverse_consolidate_active_grade_buckets(apps, schema_editor):
    # No deterministic way to restore split active rows after consolidation.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_historicalproduct_unbatched_stock_quantity_and_more"),
    ]

    operations = [
        migrations.RunPython(consolidate_active_grade_buckets, reverse_consolidate_active_grade_buckets),
        migrations.AddConstraint(
            model_name="productbatch",
            constraint=models.UniqueConstraint(
                fields=("product", "grade"),
                condition=models.Q(is_active=True),
                name="unique_active_grade_per_product",
            ),
        ),
    ]
