# Generated by Django 6.0.1 on 2026-05-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_enable_trigram_extension'),
        ('products', '0013_surplusdeal_surplus_quantity'),
    ]

    operations = [
    ]
