# Generated by Django 6.0.1 on 2026-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_surplusdeal_surplus_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organic_certified',
            field=models.BooleanField(default=False, help_text='Mark if this product is certified organic.'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='organic_certified',
            field=models.BooleanField(default=False, help_text='Mark if this product is certified organic.'),
        ),
    ]
