# Generated by Django 6.0.1 on 2026-04-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_review'),
        ('products', '0013_consolidate_active_grade_buckets_and_more'),
    ]

    operations = [
    ]
