# Generated by Django 6.0.1 on 2026-05-04 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _certificate_name_for_category(category_name):
    name = (category_name or '').lower()
    if 'egg' in name or 'poultry' in name or 'chicken' in name:
        return 'Organic Chickens'
    if 'dairy' in name or 'meat' in name or 'cattle' in name:
        return 'Organic Cattle'
    return 'Organic Crops'


def forwards(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    OrganicCertificate = apps.get_model('products', 'OrganicCertificate')

    for product in Product.objects.filter(organic_certified=True):
        category_name = ''
        if getattr(product, 'category_id', None):
            category_name = product.category.name
        certificate = OrganicCertificate.objects.create(
            producer=product.producer,
            name=_certificate_name_for_category(category_name),
        )
        product.organic_certificate = certificate
        product.save(update_fields=['organic_certificate'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_organic_certified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganicCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organic_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='organic_certificate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.organiccertificate'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='organic_certificate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.organiccertificate'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='organic_certified',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='organic_certified',
        ),
    ]
