# Generated by Django 6.0.1 on 2026-05-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_organic_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='organic_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.organiccertificate'),
        ),
    ]
