# Generated by Django 6.0.1 on 2026-05-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_merge_20260504_1948'),
        ('products', '0016_alter_product_organic_certificate'),
    ]

    operations = [
    ]
