# Generated by Django 6.0.1 on 2026-05-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_merge_20260505_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='organic_certificate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Select the organic certificate that applies to this product.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.organiccertificate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='organic_certificate',
            field=models.ForeignKey(blank=True, help_text='Select the organic certificate that applies to this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.organiccertificate'),
        ),
    ]
