# Generated by Django 6.0.1 on 2026-05-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_merge_20260505_1024'),
        ('products', '0018_alter_historicalproduct_organic_certificate_and_more'),
    ]

    operations = [
    ]
