# Generated by Django 6.0.1 on 2026-05-05 18:23

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_educationalpost_image_and_more'),
        ('products', '0019_merge_20260505_1037'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='farm',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='farm_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='prod_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='produ_desc_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
