# Generated by Django 6.0.1 on 2026-05-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_review_history'),
        ('products', '0019_merge_20260505_1037'),
    ]

    operations = [
    ]
