# Generated by Django 6.0.1 on 2026-05-07 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_settlement_models'),
        ('products', '0020_merge_20260506_1523'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='uniq_active_review_per_customer_product',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('moderation_status', 'REJECTED'), _negated=True)), fields=('customer', 'product'), name='uniq_active_review_per_customer_product'),
        ),
    ]
