# Generated by Django 6.0.1 on 2026-05-07

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_farm_farm_name_gin_idx_product_prod_name_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusdeal',
            name='best_before_date',
            field=models.DateField(default=timezone.localdate, help_text='Best before date (date only).'),
            preserve_default=False,
        ),
    ]
