# Generated by Django 6.0.1 on 2026-05-07 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_comment'),
        ('products', '0020_farm_farm_name_gin_idx_product_prod_name_gin_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'is_year_round'], name='product_visibility_idx'),
        ),
    ]
