# Generated by Django 6.0.1 on 2026-05-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_product_visibility_idx'),
        ('products', '0021_surplusdeal_best_before_date'),
    ]

    operations = [
    ]
