# Generated by Django 6.0.1 on 2026-05-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_review_uniq_active_review_per_customer_product_and_more'),
        ('products', '0021_surplusdeal_best_before_date'),
    ]

    operations = [
    ]
