# Generated by Django 6.0.1 on 2026-05-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_merge_20260507_1052'),
        ('products', '0022_merge_20260507_1118'),
        ('products', '0022_merge_20260507_unified'),
    ]

    operations = [
    ]
